### ISSUE TITLE
NotFound: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by borsemayur2** [j-mendez/dfirestore#1]
Getting error on `firestore.createDocument({collection: "users"})`
I've set following env variables:
```
FIREBASE_PROJECT_ID=
FIREBASE_PROJECT_KEY=
```
```typescript
NotFound: No such file or directory (os error 2)
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at Object.opSync (deno:core/core.js:120:12)
    at openSync (deno:runtime/js/40_files.js:32:22)
    at Object.readTextFileSync (deno:runtime/js/40_read_file.js:30:18)
    at Object.get storedToken (https://deno.land/x/dfirestore@v0.1.1/config.ts:20:25)
    at Object.get token (https://deno.land/x/dfirestore@v0.1.1/config.ts:16:17)
    at Object.request (https://deno.land/x/dfirestore@v0.1.1/client.ts:37:69)
    at Object.createDocument (https://deno.land/x/dfirestore@v0.1.1/firestore.ts:73:25)
    at file:///home/mb/my/career/deno/dfirestore/mod.ts:5:17
```

**Comment by j-mendez** [comment]
@borsemayur2 thank you for the first issue in the repo! Just pushed a change to fix the issue above. We currently write to a file firebase_auth_token.json to persist the current authenticated session between processes and shutdowns. FYI if your service requires authentication make sure to use `setTokenFromEmailPassword` or `setTokenFromServiceAccount` util to establish the admin user / user for the request. You can also use `FIREBASE_TOKEN` env variable to set one before hand as well. For `setTokenFromEmailPassword` you can use the env vars `FIREBASE_AUTH_EMAIL` and `FIREBASE_AUTH_PASSWORD` to establish the user to use for the call or simply pass it in params.

The new release is.

https://deno.land/x/dfirestore@v0.1.4

Thanks!

**Comment by j-mendez** [comment]
@borsemayur2 minor issue in v0.1.4, use https://deno.land/x/dfirestore@v0.1.5

**Comment by borsemayur2** [comment]
I'm trying `v0.1.5`. Thanks.

**Comment by borsemayur2** [comment]
Getting following error. Did I miss anything?
```
{
  error: {
    code: 401,
    message: "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other...",
    status: "UNAUTHENTICATED"
  }
}
```

**Comment by borsemayur2** [comment]
> 
> 
> Getting following error. Did I miss anything?
> 
> ```
> {
>   error: {
>     code: 401,
>     message: "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other...",
>     status: "UNAUTHENTICATED"
>   }
> }
> ```

resolved using email, password auth
