### ISSUE TITLE
[Question] How to create a document with an arrayValue?

### ISSUE THREAD

**Issue by DavidBonelo** [j-mendez/dfirestore#3]
Hi, I'm trying to create a document with an `arrayValue` but I couldn't (I'm still learning 😄) can you give me an example please?

I'm trying like this:
```ts
await firestore.createDocument({
  collection: "msgdb",
  id: "test",
  value: {
    name: { stringValue: "some text" },
    info: { arrayValue: { values: [{ stringValue: "something" }, { doubleValue: 1234 }] } },
    // test: { mapValue: { fields: { testkey: { stringValue: "teststring" }, testkey2: { doubleValue: 1234 } } } },
  },
});
```
*(the mapValue worked well)*
but I get these errors: 🤔 
> Type '{ stringValue: string; }' is missing the following properties from type 'Value': nullValue, booleanValue, integerValue, doubleValue, and 6 more.deno-ts(2740)
(property) stringValue: string

> Type '{ doubleValue: number; }' is missing the following properties from type 'Value': nullValue, booleanValue, integerValue, timestampValue, and 6 more.deno-ts(2740)
(property) doubleValue: number

dfirestore@v0.2.4
deno 1.11.2 (release, x86_64-pc-windows-msvc)
v8 9.1.269.35
typescript 4.3.2

**Comment by DavidBonelo** [comment]
So, looking at your code I changed this in types.ts:
```diff
// types.ts

export type ArrayValue = {
-  values: Value[];
+ values: Partial<Value>[];
};
```
and it worked, but I'm not sure if it is right 😅

**Comment by j-mendez** [comment]
> So, looking at your code I changed this in types.ts:
> 
> ```diff
> // types.ts
> 
> export type ArrayValue = {
> -  values: Value[];
> + values: Partial<Value>[];
> };
> ```
> 
> and it worked, but I'm not sure if it is right 😅

Looks good to me, want to push a PR for this change?

**Comment by j-mendez** [comment]
@DavidBonelo ^
