### ISSUE TITLE
Admin/Key authentication

### ISSUE THREAD

**Issue by kyeotic** [j-mendez/dfirestore#5]
Does this library work with private-key authentication the way the `firebase-admin` library did?

**Comment by j-mendez** [comment]
> Does this library work with private-key authentication the way the `firebase-admin` library did?

You can use the method `setTokenFromServiceAccount` to use the admin way of authenticating. You need to have the `gcloud` cli installed and it will use a service account to authenticate.

**Comment by j-mendez** [comment]
Make sure to have `GoogleService-Info.plist` in the root of the project for `setTokenFromServiceAccount`.

**Comment by kyeotic** [comment]
Hmm, the cli requirement and the filesystem requirement are both a bit of friction. It would be cool if this could take the cert in as json or base64-encoded json the way the firebase sdk does. That route has the advantage of allow secrets manegment via other sources, such as HTTP request or ENV VAR injection.

The firebase sdk isn't bundling the cli, afaik, so this should be possible with standard javascript
